# -*- coding: utf-8 -*-
"""calc

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vXr8DpdUfi_5iRg-xM1EeSf82_xoCtDa
"""

from MyLib import *

running = True

while running:
    print('Please type a valid operation from: +, -, *, /, %, **, //; or type e to Exit.')
    op = input()
    if op == 'e':
        running = False
        print('Good Bye!') 
    elif op == '+':
        print('Please input the first number:')
        a = int(input())
        print('Please input the second number:')
        b = int(input())
        print('The result is: ' + str(add(a, b)))

    elif op == '-':
        print('Please input the first number:')
        a = int(input())
        print('Please input the second number:')
        b = int(input())
        print('The result is: ' + str(subtract(a, b)))
    elif op == '*':
        print('Please input the first number:')
        a = int(input())
        print('Please input the second number:')
        b = int(input())
        print('The result is: ' + str(multiply(a, b)))
    elif op == '/':
        print('Please input the first number:')
        a = int(input())
        print('Please input the second number:')
        b = int(input())
        print('The result is: ' + str(divide(a, b)))
    elif op == '**':
        print('Please input the first number:')
        a = int(input())
        print('Please input the second number:')
        b = int(input())
        print('The result is: ' + str(exponent(a, b)))
    elif op == '%':
        print('Please input the first number:')
        a = int(input())
        print('Please input the second number:')
        b = int(input())
        print('The result is: ' + str(modulus(a, b)))
    
    elif op == '//':
        print('Please input the first number:')
        a = int(input())
        print('Please input the second number:')
        b = int(input())
        print('The result is: ' + str(intDivision(a, b)))