# -*- coding: utf-8 -*-
"""ColetonF_MNISTDigitsNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19ZY_NBKma75dq2YWaNDNWl2d1tNsqx-o
"""

import numpy as np

"""Loading the MNIST data set"""

from keras.datasets import mnist
#to get 60k training images
(train_images, train_labels), (test_images, test_labels)=mnist.load_data()

"""Look at training set dimensions"""

print(train_images.shape)
print(test_images.shape)
print(train_labels.shape)
print(test_labels.shape)

"""Visualize the dataset"""

import matplotlib.pyplot as plt
#automate to make the index easier to choose
indCh = int(input("Enter an Integer: ")) #this selects a letter from a massive list and prints it.  
image_index=indCh
print("Label: ",train_labels[image_index])
plt.imshow(train_images[image_index], cmap='Greys')
plt.show()

"""Create the model"""

from keras import models
from keras import layers
import keras.utils
from tensorflow.keras import utils as np_utils
from keras.utils.np_utils import to_categorical