# -*- coding: utf-8 -*-
"""p2-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-IIyU4zEt2hnXBBKXtakh4f9VXADt4r9
"""

numList=[]
for i in range(1,100):  #Loop that generates numbers 1 - 100
    numList.append(i) # adds numbers to the list
s=sum(numList) 
l=len(numList)
avg=s/l #calculates the average
print("Average:",avg)