# -*- coding: utf-8 -*-
"""p2-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KFbm_PiVbx1_v_8iUinVe_rAx-eYV4dJ
"""

n=int(input("How many numbers would you like to average:")) #User says how many numbers are in list
numList=[] #Makes a list for storing values
choice=0
for i in range(0,n):
    choice=int(input("Enter Number:"))
    numList.append(choice)
s=sum(numList)
avg=s/n
print("Average: ",avg)