# -*- coding: utf-8 -*-
"""p2-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hObXiYHg8BFo4q_T-e36VCkJ_8cNfkda
"""

names=["Alice","Bob","Cindy","Don","Ellen"]   #List containing names
grades=[[80,90,70,100,60],[70,75,88,77,82],[60,70,90,80,80],[66,76,76,69,81],[85,88,78,82,68]] #List containg grades
dic=dict(zip(names,grades)) #creates a dictionary combining above lists
avg={}
for i in dic.keys():
    sGrades=dic[i]
    avg[i]=sum(sGrades)/len(sGrades)
ma=max(dic.values())
best=""
for i in dic.keys(): #Finds the name of student who got highest avg
    if(dic[i]==ma):
        best=i
print(best)