# -*- coding: utf-8 -*-
"""p2-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AWekeIlVDB_v6_rykP0jIZM-hYKBI6ve
"""

names=["Alice","Bob","Cindy","Don","Ellen"]   #List containing names
grades=[[80,90,70,100,60],[70,75,88,77,82],[60,70,90,80,80],[66,76,76,69,81],[85,88,78,82,68]] #List containg grades
dic=dict(zip(names,grades)) #creates a dictionary combining both above lists
avg={}
for i in dic.keys():
    sGrades=dic[i]
    avg[i]=sum(sGrades)/len(sGrades)
gradescale={}#Creates a dictonary that stores letter grades. 
for i in avg.keys(): 
    if( avg[i]>=90 and avg[i]<=100):
        gradescale[i]="A"
    elif(avg[i]>=80 and avg[i]<=89):
        gradescale[i]="B"
    elif(avg[i]>=70 and avg[i]<=79):
        gradescale[i]="C"
    elif(avg[i]>=60 and avg[i]<=69):
        gradescale[i]="D"
    elif(avg[i]>=0 and avg[i]<=59):
        gradescale[i]="F"
      
for i in gradescale.keys():
    print(i,gradescale[i])