# -*- coding: utf-8 -*-
"""p3-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O9b-uKli4BBeYNpftLs-tRDSmOEAmm_G
"""

import os
import sys

path = "/content/UserLog" # Set the string to the location of your UserLog
fileList = list(os.listdir(path))

fileInfo = dict()
for file in fileList: #Calculate size for all the files. 
    size = os.stat(file)
    fileInfo[file] = size

count = 0
for item in fileInfo:
    print("File name: {:15s} File Size: {:d} Bytes".format(item,fileInfo[item].st_size))
    count += fileInfo[item].st_size
print ("{:15d} Bytes in total".format(count))