# -*- coding: utf-8 -*-
"""p3-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cV9cIUw6EqOr7rZK-PzZKklUQG-P0MJf
"""

import os
import sys
import re 
 
path = "/content/UserLog/" # Set the string to the location of your UserLog
fileList = (os.listdir(path))
 
userInfoDict = dict() 

for file in fileList:
    if file.endswith(".txt"):
      f = open(path + file, "r")
      data = f.read()
      words = data.split(' ') 
      firstName = words[0]
      lastName = words[1] 
      email = re.findall('\S+@\S+\.\S{3}',data)
      ip = re.findall( r'[0-9]+(?:\.[0-9]+){3}', data)
      details = [firstName,lastName,ip[0]] 
      userInfoDict[email[0]] = details 


file = open("/content/Destination/myData.txt", "w")  # Set the string to the location where you wish to create your myData.txt file
file.write(str(userInfoDict)) 
file.close() 
 
print(userInfoDict)