# -*- coding: utf-8 -*-
"""p3-py.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r76yyk53510TtJ_rJ-5Ps2VDURH3WYlp
"""

import os
import sys
import re 

f = open("/content/Destination/myData.txt", "r+")# Set the string to the location of your myData.txt file
data = f.read()
data = data.strip('{}\'')
dataSplit = data.split('],')

initDict = {};
for user in dataSplit:
  splitUser = user.replace("'", "").replace("[", "").replace("]","").split(':')
  email = splitUser[0].strip()
  infoSplit = splitUser[1].split(',')
  firstName = infoSplit[0].strip()
  lastName = infoSplit[1].strip()
  ip = infoSplit[2].strip()

  initDict[email] = [firstName, lastName, ip]

fileString = ''
for user in initDict:
  infoList = (initDict.get(user))
  fileString += user + ":" + infoList[0] + ":" + infoList[1] + ":" + infoList[2] + "\n"
  
print (fileString)
file = open("/content/Destination/userInfo.txt", "w")# Set the string to wherever you want your userInfo file to be created
file.write(str(fileString)) 
file.close()